#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################

source bashlets locale::it::defs


function __bashlets::locale::it::comune::entries()
{
    declare -l match="$1"
    # http://www.indicepa.gov.it/documentale/n-opendata.php
    # TODO: implement caching
    curl -s "$BASHLETS_LOCALE_IT_COMUNE_ENDPOINT" | \
        awk -F'\t' "
            tolower(\$2) ~ /^comune di $match/ { 
                printf \"%s:%s:%s:%s:%s\n\", \$1, \$2, \$6, \$7, \$8
            }"
}

#@method
function bashlets::locale::it::comune::name()
{
    __bashlets::locale::it::comune::entries "$1" | cut -d: -f2
}

#@method
function bashlets::locale::it::comune::cap()
{
    __bashlets::locale::it::comune::entries "$1" | cut -d: -f3
}

#@method
function bashlets::locale::it::comune::province()
{
    __bashlets::locale::it::comune::entries "$1" | cut -d: -f4
}

#@method
function bashlets::locale::it::comune::region()
{
    __bashlets::locale::it::comune::entries "$1" | cut -d: -f5
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
